- name: 7-Add config block "Frontend" https traffic in {{ haproxy_cfg }}
  blockinfile:
    dest: "{{ haproxy_cfg }}"
    insertafter: EOF
    block: |
    
      ### Backend

              backend be_https
                  server    server03  server03:443  check
        
              backend be_server01
                  server    server01  server01:443  check
        
              backend be_server02
                  balance roundrobin
                  server    server02  server02:443  check
                  server    server04  server02:443  check

- lineinfile:
    dest: "{{ haproxy_cfg }}"
    state: absent
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"

- lineinfile:
    dest: "{{ haproxy_cfg }}"
    state: absent
    regexp: "# END ANSIBLE MANAGED BLOCK"
