---

    - name: №14 Add apt-key for jitsi
      apt_key:
        url: https://download.jitsi.org/jitsi-key.gpg.key
        state: present
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

    - apt_repository:
        repo: "deb https://download.jitsi.org stable/"
        state: present
